import type { AssetState } from '../../../types/portfolio'

/**
 * Build a minimal AssetState with overrides for tab component tests.
 * All fields are set to safe defaults — override only what the test needs.
 */
export function buildAssetState(overrides?: Partial<AssetState>): AssetState {
  return {
    metrics: {
      asset: 'EURUSD',
      current_value: 100000,
      settled_value: 95000,
      mtm_value: 100500,
      total_return: 3.25,
      settled_return: 2.0,
      mtm_return: 3.5,
      drawdown: -1.5,
      profit_factor: 1.85,
      win_rate: 0.62,
      n_trades: 45,
      n_signals: 180,
      signal_distribution: { BUY: 80, SELL: 60, FLAT: 40 },
      mean_confidence: 68.5,
      mean_prob_long: 0.55,
      mean_prob_short: 0.42,
      current_price: 1.1050,
      last_signal_date: '2026-07-02T12:00:00',
      monthly_pf: 0.5,
      position: null,
      current_sl_mult: 2.5,
      current_tp_mult: 1.5,
      trade_log: [],
      feature_stability: {
        jaccard_top_10: 0.85,
        spearman_rank_corr: 0.72,
        penalty: 0.05,
        window_id: 'w-042',
      },
      exit_reasons: {
        tp_rate: 0.2,
        sl_rate: 0.5,
        breakeven_rate: 0.05,
        flip_rate: 0.15,
        expiry_rate: 0.1,
        avg_r: 0.35,
      },
      archetype_stats: {
        trend_follow: { n: 20, win_rate: 0.65, avg_r: 0.8, sl_rate: 0.4, tp_rate: 0.25 },
        mean_reversion: { n: 15, win_rate: 0.55, avg_r: 0.5, sl_rate: 0.5, tp_rate: 0.15 },
      },
      meta_inference: null,
      scale_out_active: false,
      remaining_fraction: 1,
      scale_out_tiers: null,
      psi_drift: {
        per_feature: [
          { feature: 'mom_21d', psi: 0.08, classification: 'moderate', trend: 'rising', importance_score: 0.3 },
          { feature: 'carry', psi: 0.02, classification: 'low', trend: 'stable', importance_score: 0.2 },
        ],
        worst_classification: 'moderate',
        moderate_count: 1,
        severe_count: 0,
        psi_ok: true,
        penalty: 0.1,
      },
      sharpe_ratio: 1.25,
      psr_gt_0: 0.95,
      psr_gt_1: 0.45,
      min_trl: 30.5,
      crs: 0.88,
      hhi: 0.12,
    },
    halt: {
      halted: false,
      reasons: [],
      hard_reasons: [],
      soft_warnings: [],
      drawdown_ok: true,
      monthly_pf_ok: true,
      drought_ok: true,
      drift_ok: true,
      narrative_ok: true,
      liquidity_ok: true,
      psi_ok: true,
    },
    validity_state: 'GREEN',
    validity_exposure: 0.85,
    last_signal: {
      date: '2026-07-02T12:00:30',
      prob_long: 0.68,
      prob_short: 0.28,
      signal: 'BUY',
      confidence: 68,
      close_price: 1.1050,
    },
    gate_override: false,
    signal_flip: false,
    final_signal: 'BUY',
    execution_state: 'ACTIVE',
    sl_mult: 2.5,
    tp_mult: 1.5,
    meta_confidence: null,
    meta_decision: null,
    feature_stability_jaccard: 0.85,
    feature_stability_spearman: 0.72,
    sell_only: false,
    tripwire_active: false,
    liquidity_regime: 'NORMAL',
    liquidity_sl_mult: 1.0,
    liquidity_size_scalar: 1.0,
    narrative_sl_mult: 1.0,
    narrative_size_scalar: 1.0,
    narrative_regime: 'RISK_ON',
    narrative_stale: false,
    regime_geometry: { TREND: { sl_mult: 2.0, tp_mult: 2.5 }, RANGING: { sl_mult: 3.0, tp_mult: 1.5 } },
    soft_warnings: [],
    stop_out_last_side: null,
    stop_out_last_cycle: null,
    last_regime_long_prob: 0.62,
    last_regime_label: 'TREND',
    sizing_chain: null,
    total_exits: 45,
    sl_exits: 22,
    sl_hit_rate: 0.4889,
    ...overrides,
  }
}
