from features.contract import FeatureContract

FEATURE_CONTRACT_VALIDATION = True

ASSET_LABEL_PARAMS: dict[str, dict] = {
    "BTC": {"pt": 1.51, "sl": 0.58, "vol_method": "atr", "atr_period": 7},
    "ES": {"pt": 5.74, "sl": 1.91},
    "NQ": {"pt": 6.12, "sl": 2.04},
    "IWM": {"pt": 2.0, "sl": 2.0},
    "VIX": {"pt": 1.5, "sl": 1.5},
    "EURAUD": {"pt": 1.77, "sl": 0.54, "vol_method": "atr", "atr_period": 14},
    "GC": {"pt": 4.0, "sl": 1.0, "vol_method": "atr", "atr_period": 14},
    "AUDJPY": {"pt": 2.01, "sl": 0.52, "vol_method": "atr", "atr_period": 14},
    "USDCAD": {"pt": 3.90, "sl": 1.30, "vol_method": "atr", "atr_period": 14},
    "CHFJPY": {"pt": 2.0, "sl": 2.0, "vol_method": "atr", "atr_period": 14},
    "EURCAD": {"pt": 2.12, "sl": 0.71, "vol_method": "atr", "atr_period": 14},
    "USDJPY": {"pt": 1.97, "sl": 0.52, "vol_method": "atr", "atr_period": 14},
    "GBPCAD": {"pt": 4.34, "sl": 1.45, "vol_method": "atr", "atr_period": 14},
    # Research assets (default EWM vol for backward compatibility)
    "NZDJPY": {"pt": 2.02, "sl": 0.51},
    "CADJPY": {"pt": 1.65, "sl": 0.52},
    "GBPJPY": {"pt": 2.22, "sl": 0.50},
    "USDCHF": {"pt": 3.0, "sl": 0.85},
    "GBPUSD": {"pt": 1.97, "sl": 0.52},
    "EURUSD": {"pt": 1.5, "sl": 3.0},  # REMOVED from trading 2026-06-20
    "AUDUSD": {"pt": 4.24, "sl": 1.41},
    "NZDUSD": {"pt": 3.87, "sl": 1.29},
    "EURGBP": {"pt": 2.0, "sl": 2.0},
    "EURJPY": {"pt": 2.0, "sl": 2.0},
    "EURCHF": {"pt": 3.0, "sl": 1.0},
    "GBPAUD": {"pt": 3.0, "sl": 1.0},
    "AUDCAD": {"pt": 2.0, "sl": 2.0},
    "AUDNZD": {"pt": 1.0, "sl": 2.0},  # REMOVED from trading 2026-06-20
    "EURNZD": {"pt": 3.36, "sl": 1.12},
    "GBPNZD": {"pt": 1.0, "sl": 3.0},  # REMOVED from trading 2026-06-20
    "GBPCHF": {"pt": 2.45, "sl": 0.82},
    "CADCHF": {"pt": 4.0, "sl": 1.0},
    "NZDCAD": {"pt": 5.48, "sl": 1.83},
    "NZDCHF": {"pt": 4.0, "sl": 1.0},
    "AUDCHF": {"pt": 3.5, "sl": 2.75},  # REMOVED from trading 2026-06-20
    "DJI": {"pt": 4.0, "sl": 0.5},
    "CL": {"pt": 2.0, "sl": 2.0},
}

FEATURE_REGISTRY: dict[str, FeatureContract] = {
    "BTC-USD": FeatureContract(
        ticker="BTC-USD",
        name="BTC",
        contract_prefix="btc-usd",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["BTC"]["pt"], ASSET_LABEL_PARAMS["BTC"]["sl"]],
            "vertical_barrier": 20,
            "vol_method": ASSET_LABEL_PARAMS["BTC"].get("vol_method", "ewm_100"),
            "atr_period": ASSET_LABEL_PARAMS["BTC"].get("atr_period", 14),
        },
        macro_filters=("rate_diff", "2y_yield_delta_63", "vix_delta_5", "dxy_mom_21", "vix_ma21"),
        price_mom_windows=(10, 21, 63),
        vs_spy_windows=(),
    ),
    "GC=F": FeatureContract(
        ticker="GC=F",
        name="GC",
        contract_prefix="gc=f",
        label_type="fwd60",
        label_params={"window": 60, "threshold": 0.02},
        macro_filters=("real_yield_delta_63", "breakeven_delta_63", "dxy_mom_63"),
        price_mom_windows=(63,),
        vs_spy_windows=(),
    ),
    "CADJPY=X": FeatureContract(
        ticker="CADJPY=X",
        name="CADJPY",
        contract_prefix="cadjpy=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["CADJPY"]["pt"], ASSET_LABEL_PARAMS["CADJPY"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=(
            "vix_ma21",
            "ca_jp_spread_mom_21",
            "us_jp_10y_spread",
            "vix_delta_5",
            "ca_jp_10y_spread",
            "dxy_mom_21",
        ),
        price_mom_windows=(10, 21, 63),
        vs_spy_windows=(),
        custom_features=("dji_lead_1",),
    ),
    "NZDJPY=X": FeatureContract(
        ticker="NZDJPY=X",
        name="NZDJPY",
        contract_prefix="nzdjpy=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["NZDJPY"]["pt"], ASSET_LABEL_PARAMS["NZDJPY"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("vix_ma21", "vix_delta_5", "us_jp_10y_spread"),
        price_mom_windows=(21,),
        vs_spy_windows=(),
        custom_features=("dji_lead_1",),
    ),
    "USDCAD=X": FeatureContract(
        ticker="USDCAD=X",
        name="USDCAD",
        contract_prefix="usdcad=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["USDCAD"]["pt"], ASSET_LABEL_PARAMS["USDCAD"]["sl"]],
            "vertical_barrier": 20,
            "vol_method": ASSET_LABEL_PARAMS["USDCAD"].get("vol_method", "ewm_100"),
            "atr_period": ASSET_LABEL_PARAMS["USDCAD"].get("atr_period", 14),
        },
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
        custom_features=("dji_lead_1",),
    ),
    "EURAUD=X": FeatureContract(
        ticker="EURAUD=X",
        name="EURAUD",
        contract_prefix="euraud=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["EURAUD"]["pt"], ASSET_LABEL_PARAMS["EURAUD"]["sl"]],
            "vertical_barrier": 20,
            "vol_method": ASSET_LABEL_PARAMS["EURAUD"].get("vol_method", "ewm_100"),
            "atr_period": ASSET_LABEL_PARAMS["EURAUD"].get("atr_period", 14),
        },
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
        custom_features=("dji_lead_1",),
    ),
    "AUDJPY=X": FeatureContract(
        ticker="AUDJPY=X",
        name="AUDJPY",
        contract_prefix="audjpy=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["AUDJPY"]["pt"], ASSET_LABEL_PARAMS["AUDJPY"]["sl"]],
            "vertical_barrier": 20,
            "vol_method": ASSET_LABEL_PARAMS["AUDJPY"].get("vol_method", "ewm_100"),
            "atr_period": ASSET_LABEL_PARAMS["AUDJPY"].get("atr_period", 14),
        },
        macro_filters=("vix_ma21", "vix_delta_5", "us_jp_10y_spread"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
        custom_features=("nzdjpy_lead_3", "dji_lead_1"),
    ),
    "GBPJPY=X": FeatureContract(
        ticker="GBPJPY=X",
        name="GBPJPY",
        contract_prefix="gbpjpy=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["GBPJPY"]["pt"], ASSET_LABEL_PARAMS["GBPJPY"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("vix_ma21", "vix_delta_5", "us_jp_10y_spread"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
        custom_features=("dji_lead_1",),
    ),
    "USDJPY=X": FeatureContract(
        ticker="USDJPY=X",
        name="USDJPY",
        contract_prefix="usdjpy=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["USDJPY"]["pt"], ASSET_LABEL_PARAMS["USDJPY"]["sl"]],
            "vertical_barrier": 20,
            "vol_method": ASSET_LABEL_PARAMS["USDJPY"].get("vol_method", "ewm_100"),
            "atr_period": ASSET_LABEL_PARAMS["USDJPY"].get("atr_period", 14),
        },
        macro_filters=("vix_ma21", "vix_delta_5", "us_jp_10y_spread", "dxy_mom_21"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
        custom_features=("gc_lead_1",),
    ),
    "USDCHF=X": FeatureContract(
        ticker="USDCHF=X",
        name="USDCHF",
        contract_prefix="usdchf=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["USDCHF"]["pt"], ASSET_LABEL_PARAMS["USDCHF"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
        custom_features=("gc_lead_1",),
    ),
    "GBPUSD=X": FeatureContract(
        ticker="GBPUSD=X",
        name="GBPUSD",
        contract_prefix="gbpusd=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["GBPUSD"]["pt"], ASSET_LABEL_PARAMS["GBPUSD"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "EURUSD=X": FeatureContract(
        ticker="EURUSD=X",
        name="EURUSD",
        contract_prefix="eurusd=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["EURUSD"]["pt"], ASSET_LABEL_PARAMS["EURUSD"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5", "real_yield_delta_63"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "AUDUSD=X": FeatureContract(
        ticker="AUDUSD=X",
        name="AUDUSD",
        contract_prefix="audusd=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["AUDUSD"]["pt"], ASSET_LABEL_PARAMS["AUDUSD"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "NZDUSD=X": FeatureContract(
        ticker="NZDUSD=X",
        name="NZDUSD",
        contract_prefix="nzdusd=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["NZDUSD"]["pt"], ASSET_LABEL_PARAMS["NZDUSD"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5"),
        price_mom_windows=(21, 63, 126),
        vs_spy_windows=(),
    ),
    "EURGBP=X": FeatureContract(
        ticker="EURGBP=X",
        name="EURGBP",
        contract_prefix="eurgbp=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["EURGBP"]["pt"], ASSET_LABEL_PARAMS["EURGBP"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "EURJPY=X": FeatureContract(
        ticker="EURJPY=X",
        name="EURJPY",
        contract_prefix="eurjpy=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["EURJPY"]["pt"], ASSET_LABEL_PARAMS["EURJPY"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("vix_ma21", "vix_delta_5", "us_jp_10y_spread"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "CHFJPY=X": FeatureContract(
        ticker="CHFJPY=X",
        name="CHFJPY",
        contract_prefix="chfjpy=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["CHFJPY"]["pt"], ASSET_LABEL_PARAMS["CHFJPY"]["sl"]],
            "vertical_barrier": 20,
            "vol_method": ASSET_LABEL_PARAMS["CHFJPY"].get("vol_method", "ewm_100"),
            "atr_period": ASSET_LABEL_PARAMS["CHFJPY"].get("atr_period", 14),
        },
        macro_filters=("vix_ma21", "vix_delta_5", "us_jp_10y_spread"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "EURCHF=X": FeatureContract(
        ticker="EURCHF=X",
        name="EURCHF",
        contract_prefix="eurchf=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["EURCHF"]["pt"], ASSET_LABEL_PARAMS["EURCHF"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5"),
        price_mom_windows=(21, 63, 126),
        vs_spy_windows=(),
    ),
    "GBPAUD=X": FeatureContract(
        ticker="GBPAUD=X",
        name="GBPAUD",
        contract_prefix="gbpaud=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["GBPAUD"]["pt"], ASSET_LABEL_PARAMS["GBPAUD"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5", "yield_slope"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "AUDCAD=X": FeatureContract(
        ticker="AUDCAD=X",
        name="AUDCAD",
        contract_prefix="audcad=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["AUDCAD"]["pt"], ASSET_LABEL_PARAMS["AUDCAD"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("ca_jp_spread_mom_21", "dxy_mom_21", "vix_ma21", "vix_delta_5"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "EURCAD=X": FeatureContract(
        ticker="EURCAD=X",
        name="EURCAD",
        contract_prefix="eurcad=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["EURCAD"]["pt"], ASSET_LABEL_PARAMS["EURCAD"]["sl"]],
            "vertical_barrier": 20,
            "vol_method": ASSET_LABEL_PARAMS["EURCAD"].get("vol_method", "ewm_100"),
            "atr_period": ASSET_LABEL_PARAMS["EURCAD"].get("atr_period", 14),
        },
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "GBPCAD=X": FeatureContract(
        ticker="GBPCAD=X",
        name="GBPCAD",
        contract_prefix="gbpcad=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["GBPCAD"]["pt"], ASSET_LABEL_PARAMS["GBPCAD"]["sl"]],
            "vertical_barrier": 20,
            "vol_method": ASSET_LABEL_PARAMS["GBPCAD"].get("vol_method", "ewm_100"),
            "atr_period": ASSET_LABEL_PARAMS["GBPCAD"].get("atr_period", 14),
        },
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "AUDNZD=X": FeatureContract(
        ticker="AUDNZD=X",
        name="AUDNZD",
        contract_prefix="audnzd=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["AUDNZD"]["pt"], ASSET_LABEL_PARAMS["AUDNZD"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5", "yield_slope"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "EURNZD=X": FeatureContract(
        ticker="EURNZD=X",
        name="EURNZD",
        contract_prefix="eurnzd=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["EURNZD"]["pt"], ASSET_LABEL_PARAMS["EURNZD"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5", "yield_slope"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "GBPNZD=X": FeatureContract(
        ticker="GBPNZD=X",
        name="GBPNZD",
        contract_prefix="gbpnzd=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["GBPNZD"]["pt"], ASSET_LABEL_PARAMS["GBPNZD"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "GBPCHF=X": FeatureContract(
        ticker="GBPCHF=X",
        name="GBPCHF",
        contract_prefix="gbpchf=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["GBPCHF"]["pt"], ASSET_LABEL_PARAMS["GBPCHF"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5", "yield_slope"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "CADCHF=X": FeatureContract(
        ticker="CADCHF=X",
        name="CADCHF",
        contract_prefix="cadchf=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["CADCHF"]["pt"], ASSET_LABEL_PARAMS["CADCHF"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("ca_jp_spread_mom_21", "dxy_mom_21", "vix_ma21", "vix_delta_5", "yield_slope"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "NZDCAD=X": FeatureContract(
        ticker="NZDCAD=X",
        name="NZDCAD",
        contract_prefix="nzdcad=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["NZDCAD"]["pt"], ASSET_LABEL_PARAMS["NZDCAD"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "NZDCHF=X": FeatureContract(
        ticker="NZDCHF=X",
        name="NZDCHF",
        contract_prefix="nzdchf=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["NZDCHF"]["pt"], ASSET_LABEL_PARAMS["NZDCHF"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "AUDCHF=X": FeatureContract(
        ticker="AUDCHF=X",
        name="AUDCHF",
        contract_prefix="audchf=x",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["AUDCHF"]["pt"], ASSET_LABEL_PARAMS["AUDCHF"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "^DJI": FeatureContract(
        ticker="^DJI",
        name="DJI",
        contract_prefix="^dji",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["DJI"]["pt"], ASSET_LABEL_PARAMS["DJI"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("rate_diff", "vix_ma21", "dxy_mom_21", "breakeven_delta_63"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
        custom_features=(),
    ),
    "CL=F": FeatureContract(
        ticker="CL=F",
        name="CL",
        contract_prefix="cl=f",
        label_type="fwd60",
        label_params={"window": 60, "threshold": 0.02},
        macro_filters=("dxy_mom_21", "real_yield_delta_63", "vix_ma21"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "ES=F": FeatureContract(
        ticker="ES=F",
        name="ES",
        contract_prefix="es=f",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["ES"]["pt"], ASSET_LABEL_PARAMS["ES"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("rate_diff", "vix_ma21", "dxy_mom_21", "breakeven_delta_63"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "NQ=F": FeatureContract(
        ticker="NQ=F",
        name="NQ",
        contract_prefix="nq=f",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["NQ"]["pt"], ASSET_LABEL_PARAMS["NQ"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("rate_diff", "vix_ma21", "dxy_mom_21", "breakeven_delta_63"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "IWM": FeatureContract(
        ticker="IWM",
        name="IWM",
        contract_prefix="iwm",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["IWM"]["pt"], ASSET_LABEL_PARAMS["IWM"]["sl"]],
            "vertical_barrier": 20,
        },
        macro_filters=("rate_diff", "vix_ma21", "dxy_mom_21"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "^VIX": FeatureContract(
        ticker="^VIX",
        name="VIX",
        contract_prefix="^vix",
        label_type="tb20",
        label_params={
            "pt_sl": [ASSET_LABEL_PARAMS["VIX"]["pt"], ASSET_LABEL_PARAMS["VIX"]["sl"]],
            "vertical_barrier": 10,
        },
        macro_filters=("dxy_mom_21", "vix_ma21"),
        price_mom_windows=(5, 10, 21),
        vs_spy_windows=(),
    ),
}
