from features.contract import FeatureContract

ASSET_LABEL_PARAMS: dict[str, dict[str, float]] = {
    "BTC": {"pt": 3.0, "sl": 1.5},
    "EURAUD": {"pt": 2.5, "sl": 1.0},
    "GC": {"pt": 4.0, "sl": 1.2},
    "NZDJPY": {"pt": 2.5, "sl": 1.0},
    "CADJPY": {"pt": 3.5, "sl": 0.8},
    "AUDJPY": {"pt": 2.5, "sl": 1.0},
    "USDCAD": {"pt": 2.5, "sl": 1.0},
    "GBPJPY": {"pt": 2.5, "sl": 1.0},
    "USDJPY": {"pt": 2.5, "sl": 1.0},
    "USDCHF": {"pt": 2.5, "sl": 1.0},
    "GBPUSD": {"pt": 2.5, "sl": 1.0},
}

FEATURE_REGISTRY: dict[str, FeatureContract] = {
    "BTC-USD": FeatureContract(
        ticker="BTC-USD", name="BTC",
        label_type="tb20",
        label_params={"pt_sl": [ASSET_LABEL_PARAMS["BTC"]["pt"], ASSET_LABEL_PARAMS["BTC"]["sl"]], "vertical_barrier": 20},
        macro_filters=("rate_diff", "2y_yield_delta_63", "vix_delta_5", "dxy_mom_21", "vix_ma21"),
        price_mom_windows=(10, 21, 63),
        vs_spy_windows=(21, 63),
    ),
    "GC=F": FeatureContract(
        ticker="GC=F", name="GC",
        label_type="fwd60",
        label_params={"window": 60, "threshold": 0.02},
        macro_filters=("real_yield_delta_63", "breakeven_delta_63", "dxy_mom_63"),
        price_mom_windows=(63,),
        vs_spy_windows=(),
    ),
    "CADJPY=X": FeatureContract(
        ticker="CADJPY=X", name="CADJPY",
        label_type="tb20",
        label_params={"pt_sl": [ASSET_LABEL_PARAMS["CADJPY"]["pt"], ASSET_LABEL_PARAMS["CADJPY"]["sl"]], "vertical_barrier": 20},
        macro_filters=("vix_ma21", "ca_jp_spread_mom_21", "us_jp_10y_spread", "vix_delta_5", "ca_jp_10y_spread", "dxy_mom_21"),
        price_mom_windows=(10, 21, 63),
        vs_spy_windows=(),
    ),
    "NZDJPY=X": FeatureContract(
        ticker="NZDJPY=X", name="NZDJPY",
        label_type="tb20",
        label_params={"pt_sl": [ASSET_LABEL_PARAMS["NZDJPY"]["pt"], ASSET_LABEL_PARAMS["NZDJPY"]["sl"]], "vertical_barrier": 20},
        macro_filters=("vix_ma21", "vix_delta_5", "us_jp_10y_spread"),
        price_mom_windows=(21,),
        vs_spy_windows=(),
    ),
    "USDCAD=X": FeatureContract(
        ticker="USDCAD=X", name="USDCAD",
        label_type="tb20",
        label_params={"pt_sl": [ASSET_LABEL_PARAMS["USDCAD"]["pt"], ASSET_LABEL_PARAMS["USDCAD"]["sl"]], "vertical_barrier": 20},
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "EURAUD=X": FeatureContract(
        ticker="EURAUD=X", name="EURAUD",
        label_type="tb20",
        label_params={"pt_sl": [ASSET_LABEL_PARAMS["EURAUD"]["pt"], ASSET_LABEL_PARAMS["EURAUD"]["sl"]], "vertical_barrier": 20},
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "AUDJPY=X": FeatureContract(
        ticker="AUDJPY=X", name="AUDJPY",
        label_type="tb20",
        label_params={"pt_sl": [ASSET_LABEL_PARAMS["AUDJPY"]["pt"], ASSET_LABEL_PARAMS["AUDJPY"]["sl"]], "vertical_barrier": 20},
        macro_filters=("vix_ma21", "vix_delta_5", "us_jp_10y_spread"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "GBPJPY=X": FeatureContract(
        ticker="GBPJPY=X", name="GBPJPY",
        label_type="tb20",
        label_params={"pt_sl": [ASSET_LABEL_PARAMS["GBPJPY"]["pt"], ASSET_LABEL_PARAMS["GBPJPY"]["sl"]], "vertical_barrier": 20},
        macro_filters=("vix_ma21", "vix_delta_5", "us_jp_10y_spread"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "USDJPY=X": FeatureContract(
        ticker="USDJPY=X", name="USDJPY",
        label_type="tb20",
        label_params={"pt_sl": [ASSET_LABEL_PARAMS["USDJPY"]["pt"], ASSET_LABEL_PARAMS["USDJPY"]["sl"]], "vertical_barrier": 20},
        macro_filters=("vix_ma21", "vix_delta_5", "us_jp_10y_spread", "dxy_mom_21"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "USDCHF=X": FeatureContract(
        ticker="USDCHF=X", name="USDCHF",
        label_type="tb20",
        label_params={"pt_sl": [ASSET_LABEL_PARAMS["USDCHF"]["pt"], ASSET_LABEL_PARAMS["USDCHF"]["sl"]], "vertical_barrier": 20},
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
    "GBPUSD=X": FeatureContract(
        ticker="GBPUSD=X", name="GBPUSD",
        label_type="tb20",
        label_params={"pt_sl": [ASSET_LABEL_PARAMS["GBPUSD"]["pt"], ASSET_LABEL_PARAMS["GBPUSD"]["sl"]], "vertical_barrier": 20},
        macro_filters=("rate_diff", "dxy_mom_21", "vix_ma21", "vix_delta_5"),
        price_mom_windows=(21, 63),
        vs_spy_windows=(),
    ),
}
